#!/usr/bin/env bash
set -xe

APP_DIR=$(cd $(dirname "${BASH_SOURCE[0]}")/.. && pwd)
GIT_REPO="https://github.com/substrate-developer-hub/substrate-developer-hub.github.io.git"
PROJECT_BUILD_DIR="build/substrate-developer-hub.github.io"

HTPASSWD='parity-devhub:$apr1$CJZJktOW$PEHfLAfsglPPvjnOhuIuV.'
HTACCESS="AuthUserFile /app/.htpasswd\n
AuthType Basic\n
AuthName \"Restricted Access\"\n
Require valid-user"

# cmd for building
echo $APP_DIR
pushd $APP_DIR > /dev/null

cd website
yarn install
NODE_ENV=staging GIT_REV=`git rev-parse --short HEAD` yarn build

# Heroku will pick up from `staging` branch
cd $PROJECT_BUILD_DIR
git init .
git remote add origin $GIT_REPO
git checkout -b staging

# Adding necessary files for using heroku php buildpack
echo '<?php header("Location: /index.html");?>' > index.php
echo $HTPASSWD > .htpasswd
echo -e $HTACCESS > .htaccess

# Everything needs to be done locally should be completed by this point. Push the `staging` branch
# in github. Notice we have generated a keypair and set to deploy keys with write access in github.
git add .
git commit -m "Updated"
git push -f origin staging
popd
